"""Adding last_seen column to Contact table

Revision ID: 1ac3e378971e
Revises: 6476acfbaff1
Create Date: 2024-07-01 18:07:14.812028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ac3e378971e'
down_revision = '6476acfbaff1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Last_Seen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.drop_column('Last_Seen')

    # ### end Alembic commands ###
