"""Adding profile column to users class

Revision ID: 1e4f2ccc3ffc
Revises: 2ebf768aec28
Create Date: 2024-08-05 00:01:01.439786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e4f2ccc3ffc'
down_revision = '2ebf768aec28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Profile_pic', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('Profile_pic')

    # ### end Alembic commands ###
