"""Adding media name column to Message table

Revision ID: 2ebf768aec28
Revises: 6ab07a8a144f
Create Date: 2024-08-02 11:54:30.867909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ebf768aec28'
down_revision = '6ab07a8a144f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Media_Name', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('Media_Name')

    # ### end Alembic commands ###
