"""Adding Viewer classs

Revision ID: 6ab6de2229a0
Revises: 0a044c5d9625
Create Date: 2024-07-21 21:33:45.796529

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6ab6de2229a0'
down_revision = '0a044c5d9625'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily', schema=None) as batch_op:
        batch_op.drop_column('Type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Type', mysql.VARCHAR(length=100), nullable=False))

    # ### end Alembic commands ###
