"""empty message

Revision ID: b57b934ff829
Revises: df37f1796e65
Create Date: 2024-06-30 11:02:03.727648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b57b934ff829'
down_revision = 'df37f1796e65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Sid_id', sa.String(length=200), nullable=True))
        batch_op.create_unique_constraint(None, ['Sid_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('Sid_id')

    # ### end Alembic commands ###
