"""Rename update to daily'

Revision ID: b84196b3f897
Revises: 1ac3e378971e
Create Date: 2024-07-13 16:39:41.021198

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b84196b3f897'
down_revision = '1ac3e378971e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('update')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('update',
    sa.Column('Id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Name', mysql.VARCHAR(length=400), nullable=False),
    sa.Column('TimeStamp', mysql.DATETIME(), nullable=True),
    sa.Column('Expire', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('Owner', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['Owner'], ['users.Id'], name='update_ibfk_1'),
    sa.PrimaryKeyConstraint('Id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
