"""Adding user_key and last_seen column to user table

Revision ID: f7f6c4906cd4
Revises: c31e6ba49835
Create Date: 2024-06-19 15:56:00.172688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7f6c4906cd4'
down_revision = 'c31e6ba49835'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('User_key', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('Last_seen', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint(None, ['User_key'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('Last_seen')
        batch_op.drop_column('User_key')

    # ### end Alembic commands ###
